### PR TITLE
Add CaptureErrorWithExtra()

### PR DESCRIPTION
**Pull request by abhi11**
Enables client to set the extras field while firing a Capture() method

### CODE REVIEW

**Comment by mattrobenolt** [comment]
Awesome, thanks! Do you mind adding a test that covers this? It should be relatively trivial.

**Comment by abhi11** [comment]
What exactly do you want in the test ? 
Something like this:

```Go
func TestPacketJSONWithExtra(t *testing.T) {
	packet := &Packet{
		Project:     "1",
		EventID:     "2",
		Message:     "test",
		Timestamp:   Timestamp(time.Date(2000, 01, 01, 0, 0, 0, 0, time.UTC)),
		Level:       ERROR,
		Logger:      "com.getsentry.raven-go.logger-test-packet-json",
                Extra: map[string]interface{}{
                         "key":"value" 
                }
	}

       expected := `the expected string`
       // JSONify and check if matches expected string 
}
```
Will this suffice ?

**Comment by syndbg** [comment]
Isn't this a duplicate of #134 ?

**Comment by abhi11** [comment]
@mattrobenolt hey, this has been open for a long time.

**Comment by syndbg** [comment]
@abhi11 No progress neither here nor in #134, unfortunately.

**Comment by knabben** [comment]
Fixed on #190

**Pull request closed without merging**
