### PR TITLE
Adding support for an array of fingerprints

### PR DESCRIPTION
**Pull request by aheuermann**

### CODE REVIEW

**Comment by mattrobenolt** [comment]
Oh, oops. I somehow missed this in the previous PR. :(

Thanks for fixing!

**Comment by Sinjo** [comment]
Sorry about the bug! The string worked against Sentry 7 (which we were running at the time), and I didn't check against Sentry 8. :(

**Comment by mattrobenolt** [comment]
@Sinjo That's because sentry 7 didn't support fingerprints. :)

It's all good.

**Comment by Sinjo** [comment]
It wasn't mega documented at the time, but we were using it from https://github.com/getsentry/sentry/blob/master/CHANGES#L255

**Comment by mattrobenolt** [comment]
Ah, I guess you're right. I thought we added that in 8. :( Hard to keep track at this point.

**Comment by Sinjo** [comment]
> Hard to keep track at this point.

It's all good. Much :heart: for all the new features!

**Pull request merged**
