### PR TITLE
Changing the raven.RecoveryHandler signature

### PR DESCRIPTION
**Pull request by algogrit**
This fixes issue: https://github.com/getsentry/raven-go/issues/182

### CODE REVIEW

**Comment by gauravagarwalr** [comment]
Duplicate of https://github.com/getsentry/raven-go/pull/106

**Comment by alexflint** [comment]
This will break existing users of this library. See #193 for a backwards-compatible version.

**Comment by gauravagarwalr** [comment]
@alexflint Sure it does. The existing API itself, doesn't work well now. Does it?

**Comment by dcramer** [comment]
Closing as we merged #193

**Pull request closed without merging**
