### PR TITLE
[#111][#125] Send custom extra data

### PR DESCRIPTION
**Pull request by syndbg**
The API changes are **considerable** and the docs at https://docs.sentry.io/clients/go/ will need to be updated. I'm going to update them too. ~~WIP on that.~~

~~The PR imo is not ready for merge. I'll try and update the docs wherever needed.~~

Docs updated, I think we're good to go?

@mattrobenolt @zkanda

### CODE REVIEW

**Comment by syndbg** [comment]
Ping, anyone? @mattrobenolt

**Comment by rollcat** [comment]
Sorry for the spam, but this is relevant to my interests.

If breaking the API is a big concern, perhaps I could work on a variant with new `*WithExtra` methods? `CaptureErrorWithExtra` etc.

**Comment by syndbg** [comment]
@mattrobenolt ping

**Comment by mattrobenolt** [comment]
> If breaking the API is a big concern, perhaps I could work on a variant with new *WithExtra methods? CaptureErrorWithExtra etc.

Sorry for the delay here, I'd absolutely love to do that instead of breaking all the existing APIs.

**Comment by syndbg** [comment]
@mattrobenolt Sure, could do that in the same PR.

**Comment by syndbg** [comment]
@mattrobenolt Sorry for the delay, I've updated the PR. Added `*Extra` functions.

**Comment by syndbg** [comment]
@mattrobenolt Ping?

**Comment by knabben** [comment]
Fixed on #190

**Pull request closed without merging**
